### ISSUE TITLE
Subscribe handler not being called when performing multiple actions in parallel.

### ISSUE THREAD

**Issue by darklow** [luisvinicius167/riotux#12]
I am witnessing some weird behaviour.
Two of my riot tags are performing riotux actions on `mount` event. In the same tags I am subscribed to two different state properties. Both actions perform asynchronous calls and when asynchronous task is complete I am dispatching events to change according properties. Both state mutations are called.
The problem is that only one subscribed handler is called.
If I uncomment one or another action, then each of them works well, but not when both running in parallel.

**Comment by darklow** [comment]
I noticed same behaviour with performing one task too.
If task is asynchronous and any other actions were perfomed 

In my example below i am using websockets on my app and I have following `initSocket` action.
The first two states: `connecting` and `connecting` are dispatched correctly.

Afterwards my app calls lot of different actions and mutations and if server gets disconnected, my subscribed component handlers never get called on `disconnect` event. State mutation is called, but not subscribed component handlers. However if I don't call any other actions after `connected` state and just for test turn off server, then `disconnect` works as intended and all handlers that are subscribed to `wsState` gets called.

Looks like there riotux is some kind of singleton and you can't process multiple things or actions at parallel and riotux keeps last action state and only that is getting dispatched. Is this something that can be fixed? Thank you.

```js
riotux.Store({
    state: {
        wsState: null
    },
    mutations: {
        setWsState: function (state, value) {
            state.wsState = value;
        }
    }
});

riotux.Actions({
    initSocket: function (store) {
        // ... socket connect here

        store.dispatch('setWsState', 'connecting');

        socket.onmessage = function (message) {
            message = JSON.parse(message.data);
            riotux.action(message.state, 'onMessage', message);
        };

        socket.onopen = function () {
            store.dispatch('setWsState', 'connected');
        };
        socket.onclose = function () {
            store.dispatch('setWsState', 'disconnected');
        };
    },
});
```

**Comment by darklow** [comment]
Sorry if it is hard to understand, but in other words if you call two actions right one after each other and each action should update different store properties aka states, then only second will be dispatched to component handler because by looking at the code `_currentState` is global and being overriden right on action call.

```js
riotux.action(‘items’, ‘doSomethingAsync’, function(){ });
riotux.action(‘count’, ‘doSomethingNow’, function(){ });
```

**Comment by darklow** [comment]
I created a fix/workaround that solves my issue, could you take a look please?
Thanks.

**Comment by fkei** [comment]
👍

**Comment by darklow** [comment]
Waiting for @luisvinicius167 to comment my solution, if he agrees, I can make a PR. My fix is working great so far, tried many simultaneous actions with async requests which performs mutation on response and so far no issues.

**Comment by luisvinicius167** [comment]
Sorry for long response time! Working a lot :) I understood about this bug, very excited about your PR, I will waiting! @darklow Thank you so much! I'm thinking to create a Riotux dev tools, would be nice. Thanks bro!

**Comment by luisvinicius167** [comment]
@darklow see that: [Version 2.0](https://github.com/luisvinicius167/riotux/issues/14) :)
