### ISSUE TITLE
Cannot provide multiple arguments for trigger method

### ISSUE THREAD

**Issue by darklow** [luisvinicius167/riotux#4]
First of all thanks for the great library.

In RiotJS observables and also in RiotControl when triggering event you can specify unlimited arguments to trigger function and receive them on listener:
```js
// On observable
self.trigger('event', 1, true, {test: 123});
// On listener
obs.on('event', function(num, status, obj){
  // All arguments are present
});
```

However in riotux only first argument is forwarded to listener and rest of them are dropped.
```js
riotux.trigger('myStore', 'event', 1, 2, 3);
// On myStore:
self.on('event', function (one, two, three) {
  // two and three are undefined :(
});
```
It would be great if this library had same possibility and since it is built on top of observables I was expecting same behaviour.

I guess it could be easy change, using `apply` similarly as here:
https://github.com/jimsparkman/RiotControl/blob/master/riotcontrol.js#L15

Although I tried to fix by myself first, but didn't succeeded.

Thanks.

**Comment by luisvinicius167** [comment]
Shure, I will fix it! Thanks and I hope riotux helps you! :)

**Comment by darklow** [comment]
Yes, it helps a lot. Thanks. I started with RiotControl, but now when projects grows I need more control of how stores and view can communicate and `riotux` is perfect!

**Comment by luisvinicius167** [comment]
Yeah, same for me. I started with RiotControl too, but ```riotux``` provides much more organization to applications, I think.

**Comment by luisvinicius167** [comment]
Fixed! :+1: Now, have the same riot.observable behaviour.

**Comment by darklow** [comment]
Awesome, thank you! Just tested and new feature is working great.

**Comment by luisvinicius167** [comment]
Great! :D

**Comment by luisvinicius167** [comment]
@darklow what you think about new version of riotux? If you can send your feedback for me! Now, riotux follows flux and redux principles, not like before, that works as pub/sub.

**Comment by darklow** [comment]
@luisvinicius167 Now I got back to some JS programming and at first I was surprised that everything has changed, like a different library. But after reading new docs and trying by myself I can see how this is much more powerful and straightforward. I love new API. 
Thanks for the great work!!
