### ISSUE TITLE
Actions as store functions

### ISSUE THREAD

**Issue by nippur72** [luisvinicius167/riotux#5]
nice project, I've written something similar for `react-templates`, if you mind I would like to hear your opinion on the following ideas:

1) make actions be true functions on the store itself. So instead of calling the dispatcher with the magic string `my_action`, you call the function directly (`store.my_action(params)`). The advantage is to have full intellisense on the action parameters (assuming your IDE does support intellisense). Perhaps the store itself could be an ES6 class to exend. 

2) make the store trigger just one `update` event when the state changes. The idea is to simplify: you don't want to deal with the details of what part of the state sub-tree has changed, it's enough to know something has changed. So your store could have a "subscribe" function:
```
store.subscribe(this); // this=riot tag
// on the store:
function subscribe(tag) {
   this.on('update', ()=> tag.update() );
}
function update() {
   this.trigger('update');
}
function my_action() {
   // mutate state
   this.update();
}
```

3) you can write a wide range of debugging tools by hooking on the actions and on the update event. For example writing to console what actions have been dispatched, the params, and the state differences before/after (look at packages like `deep-diff`).

**Comment by luisvinicius167** [comment]
First of all, thanks and I hope riotux can help you, some day.I think about the concepts itself. Riotux actions are in fact "action creators" in vanilla flux definitions, I tryed simplify, making actions responsability just call store mutations for change the state. I think this way, riotux, provides more organization in your application. Your store just are a central state management and has the responsability to change state via mutations. Actions just called by Components and registered out store.

About the second ideia, I liked. So, now your component can observe the state, passing the name of the state and when the store state changes the component recieves the new state. I will study implement some way to simplify this using your idea.

Great ideia. I will work on the riotux debugging tools. It can be very useful for we. Thanks for ideas!

**Comment by nippur72** [comment]
The debugging tools are really helpful. Here is what I use after an action has been dispatched and processed:
```
// displays the differences between new and old state
function debugDiffs() {
         var oldState = ...
         var newState = ...
         var diff = require("deep-diff");      
         var diffs = diff(oldState, newState);
         if(diffs) 
         {
            _.each(diffs, function (d) {
               console.log(prettyDiff(d));
            });
         }
}

export function prettyDiff(d: deepDiff.IDiff) 
{
   try 
   {
      var path = "";
      if(d.path) path = d.path.join(".");
      if(d.index!==undefined) path = path + `[${d.index}]`;

      var value = d.item ? d.item.rhs : d.rhs; 

      var msg = "";

      switch(d.kind) {
         case "N":
            msg = `${path} = ${JSON.stringify(d.rhs)};`;
            break;

         case "E":
            msg = `${path} = ${JSON.stringify(d.rhs)}; // was: ${JSON.stringify(d.lhs)}`;
            break;

         case "D":
            msg = `delete ${path}; // was: ${JSON.stringify(d.lhs)}`;
            break;

         case "A":
            switch(d.item.kind) {
               case "N":
                  msg = `${path} = ${JSON.stringify(d.item.rhs)};`;
                  break;

               case "E":
                  msg = `${path} = ${JSON.stringify(d.item.rhs)}; // was: ${JSON.stringify(d.item.lhs)}`;
                  break;

               case "D":
                  msg = `delete ${path}; // was ${JSON.stringify(d.item.lhs)}`;
                  break;

               default:
                  msg = `array change in ${path}: ${JSON.stringify(d)}`;
            }         
            break;

         default:
            msg = `unknown diff: ${JSON.stringify(d)}`;
      }
  
      return msg;
   }
   catch(ex)
   {
      return ex.message;
   }
}
```
On `npm` there could be other (presumely better) packages for diffing objects. `deep-diff` was just the first I found. 

Keep up with the good work!

**Comment by luisvinicius167** [comment]
very good! I liked and looking to use in riotux.

**Comment by luisvinicius167** [comment]
@nippur72 Now, riotux don't depends of Riot.js observables. Works for itself. Thanks for ideia!

 https://github.com/luisvinicius167/riotux#observe-state-changes-in-your-component
