### ISSUE TITLE
Typos, naming and a question

### ISSUE THREAD

**Issue by kokujin** [luisvinicius167/riotux#7]
I have seen no example showing the ability to "time travel" like Redux.
'Mutations' Should be called 'Mutators' in my opinion.
riotux.get(state) is better than riotux.getter(state) in my opinion

You have a few typos in the docs. I could send you a pull request to correct them if you want.

**Comment by luisvinicius167** [comment]
Yes, good points! I will consider this, waiting your PR!

**Comment by luisvinicius167** [comment]
updated: getter -> get :+1:

**Comment by kokujin** [comment]
Great @luisvinicius167 . Anything on my question about Redux like Time travelling?

**Comment by luisvinicius167** [comment]
@kokujin I think to work on this feature. At now, I'm just using console.log on acitons and mutations to view. But I'll improve!
