### ISSUE TITLE
Usage question on Actions

### ISSUE THREAD

**Issue by kokujin** [luisvinicius167/riotux#8]
From the docs:
`````
var action = riotux.Actions({
  add: function ( store, number ) {
    store.dispatch('increment', number);
  }
}); 
`````
Calling an action on your component

````
riotux.action('count', 'increment', 10);
````

Is there any reason why the instance of the action is assigned to the "action" variable when it is supposed to be called from the riotux instance?

**Comment by luisvinicius167** [comment]
Hi! Thanks for the question! No reason, because you call the actions via riotux instance. I just put it beacuse I prefer, but this is not necessary.
